name: lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add actionlint problem matcher
        run: echo "::add-matcher::.github/actionlint-matcher.json"

      - name: Lint workflows
        uses: docker://rhysd/actionlint@v1.7.7
        with:
          args: -color

      - name: Lint markdown
        uses: DavidAnson/markdownlint-cli2-action@v19
        with:
          config: '.markdownlint.json'
          globs: |
            **/*.md

      - name: Lint PowerShell
        shell: pwsh
        run: Invoke-ScriptAnalyzer -Path . -Recurse -IncludeDefaultRules -ReportSummary -Severity @('Error','Warning') -EnableExit
